Repository astronomer/docs, pull requests merged in 2023-09, with the labels that each got.

#2785 Lint code datasets use case and add black borders to img
  learn/use-case-airflow-datasets-multi-team-ml.md
  static/img/examples/airflowuiview.png
  static/img/examples/datasetsview.png
  static/img/examples/use-case-airflow-ml-datasets_airflowuiview.png
  static/img/examples/use-case-airflow-ml-datasets_datasetsview.png
  static/img/examples/use-case-airflow-ml-datasets_usecaseconsumerproducerfigma.png
  static/img/examples/usecaseconsumerproducerfigma.png
Labels: kind/quick-fix

#2786 Remove direct querying examples in database guide
  learn/airflow-database.md
Labels: kind/quick-fix

#2811 Add index for orphan CLI command references
  astro/cli/astro-deployment-worker-queue-create.md
  astro/cli/astro-deployment-worker-queue-delete.md
  astro/cli/astro-deployment-worker-queue-update.md
  sidebarsAstro.js
Labels: kind/quick-fix

#2802 ELT and ML use case financial data
  learn/use-case-elt-ml-finance.md
  sidebarsLearn.js
  static/img/examples/use-case-elt-ml-finance_datasets_view.png
  static/img/examples/use-case-elt-ml-finance_finance_elt_dag_graph.png
  static/img/examples/use-case-elt-ml-finance_finance_ml_dag_graph.png
  static/img/examples/use-case-elt-ml-finance_in_finance_data_dag_graph.png
  static/img/examples/use-case-elt-ml-finance_model_result_plot.png
Labels: kind/new-doc, area/learn

#2830 [Tiny PR] Add another note about CLI upgrading to the Create your first DAG doc
  astro/create-first-dag.md
Labels: kind/quick-fix

#2831 [Tiny PR] Add default schedule to scheduling guide
  learn/cross-dag-dependencies.md
  learn/scheduling-in-airflow.md
Labels: kind/quick-fix, area/learn

#2836 [Tiny PR] Use ROOT user before `ssh` setup and package install
  astro/develop-project.md
Labels: error/wrong-info, product/cli

#2852 Add link to Airflow/dbt concept comparison in Cosmos tutorial
  learn/airflow-dbt.md
Labels: kind/quick-fix

#2838 `astro dev` add generated-index and change description
  astro/cli/astro-dev-bash.md
  astro/cli/astro-dev-init.md
  astro/cli/astro-dev-kill.md
  astro/cli/astro-dev-logs.md
  astro/cli/astro-dev-object-export.md
  astro/cli/astro-dev-object-import.md
  astro/cli/astro-dev-parse.md
  astro/cli/astro-dev-ps.md
  astro/cli/astro-dev-pytest.md
  astro/cli/astro-dev-restart.md
  astro/cli/astro-dev-run.md
  astro/cli/astro-dev-start.md
  astro/cli/astro-dev-stop.md
  astro/cli/astro-dev-upgrade-test.md
  sidebarsAstro.js
  static/img/term-icon.png
Labels: kind/enhancement, product/cli

#2878 Remove Airflow Summit 2023 Promo Banner
  src/theme/Navbar/Layout/index.js
Labels: area/docs-site, kind/quick-fix

#2870 Create table pattern with data quality checks and setup/ teardown use case
  learn/use-case-setup-teardown-data-quality.md
  sidebarsLearn.js
  static/img/examples/use-case-setup-teardown-data-quality_create_rose_table_dag_graph.png
  static/img/examples/use-case-setup-teardown-data-quality_datasets_view.png
  static/img/examples/use-case-setup-teardown-data-quality_result_plots.png
  static/img/examples/use-case-setup-teardown-data-quality_rose_classification_dag_graph.png
  static/img/examples/use-case-setup-teardown-data-quality_setup_teardown_workflow.png
  static/img/examples/use-case-setup-teardown-data-quality_validate_taskgroup.png
Labels: kind/new-doc, area/learn

#2880 [Tiny PR] Fix GH Actions Single branch template
  astro/ci-cd-templates/github-actions.md
Labels: kind/quick-fix

#2842 Add CLI output references
  astro/cli/astro-context-list.md
  astro/cli/astro-deployment-list.md
  astro/cli/astro-organization-list.md
  astro/cli/astro-organization-user-list.md
  astro/cli/astro-workspace-list.md
  astro/cli/astro-workspace-team-list.md
  astro/cli/astro-workspace-user-list.md
Labels: kind/enhancement, product/cli

#2835 Add disambiguation about custom registries for Software
  software/custom-image-registry.md
  software/install-airgapped.md
  software/registry-backend.md
Labels: error/misleading, product/software

#2877 Update Cloud IDE ML tutorial
  learn/cloud-ide-tutorial.md
  static/img/guides/cloud_ide_github_secrets.png
  static/img/tutorials/cloud-ide-tutorial_auto_dependency_sql_cells.png
  static/img/tutorials/cloud-ide-tutorial_cloud_ide_button.png
  static/img/tutorials/cloud-ide-tutorial_code_view.png
  static/img/tutorials/cloud-ide-tutorial_configure_github.png
  static/img/tutorials/cloud-ide-tutorial_create_connection.png
  static/img/tutorials/cloud-ide-tutorial_create_connection_2.png
  static/img/tutorials/cloud-ide-tutorial_create_pipeline.png
  static/img/tutorials/cloud-ide-tutorial_create_project.png
  static/img/tutorials/cloud-ide-tutorial_dag_on_astro.png
  static/img/tutorials/cloud-ide-tutorial_dependency_graph.png
  static/img/tutorials/cloud-ide-tutorial_environment_button.png
  static/img/tutorials/cloud-ide-tutorial_first_cell_output.png
  static/img/tutorials/cloud-ide-tutorial_gh_repo.png
  static/img/tutorials/cloud-ide-tutorial_new_branch.png
  static/img/tutorials/cloud-ide-tutorial_new_req.png
  static/img/tutorials/cloud-ide-tutorial_schedule_1.png
  static/img/tutorials/cloud-ide-tutorial_snowflake_conn.png
  static/img/tutorials/cloud-ide-tutorial_train_task_output.png
Labels: kind/enhancement, area/learn

#2891 Fix admonitions
  archived_software_docs/version-0.27/cli-release-notes.md
  archived_software_docs/version-0.28/cli-release-notes.md
  archived_software_docs/version-0.29/cli-release-notes.md
  archived_software_docs/version-0.29/release-notes.md
  astro/cli/release-notes.md
  astro/migrate-gcc.mdx
  astro/migrate-mwaa.mdx
  astro/release-notes.md
  software/cluster-resource-provisioning.md
  software/release-notes.md
  software_versioned_docs/version-0.30/release-notes.md
  software_versioned_docs/version-0.32/cluster-resource-provisioning.md
  software_versioned_docs/version-0.32/release-notes.md
Labels: kind/quick-fix
